[gcp_service_account]
type = "service_account"
project_id = "api-project-20248234883"
private_key_id = "64a594d469b3c84ae778db25c53ecfe3363c2be6"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC4gqqsqcM0NUSL
M+OMmH4yJZgQf+QMibQlV+omrupQCz6JfchWurWMNMFiDw6iXRgk/cSJsOhKz6Nl
G/1/UJMCIPl1RJK+XysMy3vC3I+m9rV1fVYC+bmXupyBqc4ToiY5PJlE10T+17YP
aFD1AQA9XtWVmaw3y++ZI8ARZJZzRVXIjN0c/cGeFSD/6G6taIw20wZuu5ZZIlp9
93h/5yYWhrH9xzipYIgC9HY/0+uwJi43jTuzsH9X1RTuviFrTNRLzbW93hMJjxim
YheUDi0ALacsyi+Y3JkLQkI4Iq1nEKy6Fj90szx4GnbRx2Zg6l2u9piPTUnv6Ezs
n6dWqBwJAgMBAAECggEAAPBGOLxg1jNGqtwb1ldgvfXPvxa9dNxe9pkqw2FcpwVV
nzqs8hb/TSwoBy0LLqOBV8/UJ/ymw9moS79/k74Xz1kWV8S+Z9pBVG51DdXUI73p
yKQXc8qsKWPNP8IavqISpnQi1fUv4El93zhxP/vOMeG5faozVHHUwU9LnvMHamTv
zEasRv5w4lV/N6f/b8du0klZKx08XTSdnWxYWVRQR2e7nROSVbZehhPyZIoV6kTx
xRnw1K3BY5I+ptlqDWfKiUfSge9C0MbZjp++WzGX2FACel6F+XTmvQpcnsUMFtGB
Ot0HA13HgbYQGY1bLuWcV3GA+kohrWlzJH4HmZahAQKBgQDyNBEwVcEnMXdJ6SDK
OXD/THF2e49w13olfxXpfXPZ6D/EYvYYOxkXIc6syhmuBGlv/NRKtZtphCPVNkHV
56SmnRetk0Zr6FuecYAsR0zFRa2uDyrIL5G4rQG0eqIB2Q9ayuTNy26qzLK5ppMw
x+BbkqZ+3vqxbR1TO76d3tDDAQKBgQDDBUqVhFuCT+lX4hvxzHjdeRS15NkJnngQ
GzptLw5Uv2bgsmI7kbvikeJUdgg31Lxsy+LwtXMBayefccmkDsSKKOqao4XlG+QH
56tRMPU1gNOkvT/rgZOtcXgB4XcuAnZjaM3nO2zKHidIvjIDTDcJE4E1+M5A77zS
w6gLlc5BCQKBgA8n7O9uXlDaipFocjHVWFnRacQ1RSuVgEI6ap+axxYar2rVmnq3
sAE/j1RGrUazZfmpA4vNQ3Vd3HQqGgKNpUL7z5CAB8cW2izXA2NB7u7lRlH/BvlR
6Ld6tAGcLukYsRpIWfr6wOkVOBXf85P43fQ9AAguYdeacVxU/7+XQs8BAoGBAJZi
eS4s/4fQaYbshFIEM9vNJ8xP6ZGCUuFQrdBOLgXqBsIUrK105uaDSn2I+zNaZ+aZ
nqmxsjqQz+AjFbPd8276uFaA7JpM1J3H5xLX5u7YJdxuV2Ea7a8cxcblf0rKeVKV
GdpKt8xwTijJCbYDSplEIiplb18hv4Djga1VWtRJAoGBAJan4Eul92LX+kSLtNKO
+Yz1mtPlLC1YTmyt97EeUZuRk1pV96V/OiQ0yIGkvBX25kcsU0/UUlxHVPNjkngg
DF8hWxKDIf8oO3psj4DYMtbMb+lLNUJ8T2nznpkI5icv68U7r8EF24rEhyjRwvv6
aV2Qz+etPsPRKrOBas4MflNm
-----END PRIVATE KEY-----
"""
client_email = "api-project-20248234883@api-project-20248234883.iam.gserviceaccount.com"
client_id = "103800260155382586361"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/api-project-20248234883%40api-project-20248234883.iam.gserviceaccount.com"
